FROM python:3.7.2

ENV APPLICATION_ROOT /app
RUN mkdir $APPLICATION_ROOT
WORKDIR $APPLICATION_ROOT

COPY Pipfile $APPLICATION_ROOT/Pipfile
COPY Pipfile.lock $APPLICATION_ROOT/Pipfile.lock
RUN pip install pipenv
RUN pipenv install --dev --system

ADD . $APPLICATION_ROOT
